# Generated by Django 5.2.17 on 2026-10-07 09:26

import django.db.models.deletion
from django.db import migrations, models


def seed_smartdarasa(apps, schema_editor):
    Startup = apps.get_model('staff', 'Startup')
    StartupPublicSection = apps.get_model('staff', 'StartupPublicSection')
    StartupStorySlide = apps.get_model('staff', 'StartupStorySlide')
    StartupTeamMember = apps.get_model('staff', 'StartupTeamMember')
    ServiceOffered = apps.get_model('staff', 'ServiceOffered')
    Funding = apps.get_model('staff', 'Funding')
    KPI = apps.get_model('staff', 'KPI')

    startup, _ = Startup.objects.update_or_create(
        slug='smartdarasa',
        defaults={
            'name': 'SmartDarasa',
            'startup_type': 'public',
            'description': (
                'SmartDarasa is an interactive learning platform designed to bridge the gap '
                'between theoretical and practical STEM education. The supplied brochure '
                'describes interactive 2D content, 360-degree 3D models, virtual laboratory '
                'simulations and augmented reality learning experiences, with subscription '
                'offers for schools and individual users.'
            ),
            'industry': 'Edutech',
            'website': '',
            'contact_email': '',
            'phone': '',
            'source': 'SmartDarasa startup profile brochure',
            'directory_visible': True,
            'status': 'active',
        },
    )

    sections = [
        ('The problem',
         'The brochure describes a gap between theoretical STEM lessons and practical knowledge. It reports that many schools lack equipped laboratories and identifies teacher shortages, uneven access to training and limited technology integration as barriers to students’ learning.',
         'Claims transcribed from the supplied SmartDarasa brochure; publication date not shown.', 10),
        ('The solution',
         'SmartDarasa presents classroom concepts through interactive 2D content, 360-degree 3D models, online laboratory simulations and augmented reality. The brochure says teachers can use the platform to explain complex concepts and students can explore practical experiments remotely.',
         'Product description from the supplied SmartDarasa brochure.', 20),
        ('Product and services',
         'The brochure lists 2D interactives, 3D models, virtual laboratory simulations and AR experiences. It also describes Smart Labs for schools, tablet access or leases, practical learning content and Smart APIs for integrating educational materials with other platforms.',
         'Features reported in the supplied SmartDarasa brochure.', 30),
        ('Business model',
         'The brochure describes a B2B model with subscriptions for schools, Smart Labs and API integrations. Its B2C model includes subscriptions converted to SmartDarasa coins and an ad-supported free tier. These are the models described in the brochure, not independently verified current offers.',
         'Business model stated in the supplied SmartDarasa brochure.', 40),
        ('Reported traction',
         'The brochure reports US$9,070 revenue in 2021–2022 and says sales activity was reduced after a COSTECH grant in 2022 while the product shifted toward subscriptions. It also reports visits to 15+ schools, 70 teachers and 1,500+ students from late 2020. For an unspecified “last 12 months” period, it lists 1,700+ app downloads with no marketing spend and 3,500+ website visitors.',
         'Figures and reporting periods are transcribed from the brochure; the date of the brochure is not supplied.', 50),
        ('Funding reported',
         'The brochure reports US$58,022 raised: US$24,022 from COSTECH, US$10,000 from Diamond Do Goods, US$5,000 from Amazon Web Services, US$5,000 from the Schultz Family Foundation and US$14,000 from the Mastercard Foundation. The brochure does not provide dates for these amounts.',
         'Funding sources and amounts as listed in the supplied SmartDarasa brochure.', 60),
        ('Partnerships and competitions',
         'The brochure lists partnerships with Vodacom Tanzania, Projekt Inspire and MITz Kitz. It names the German–Tanzania Startup Competition, Vodacom Digital Accelerator and UPG Biashara under competitions won.',
         'Names transcribed from the supplied SmartDarasa brochure.', 70),
        ('Milestones and expansion plan',
         'The brochure timeline lists a grant and prototype in 2019, beta release in 2020, commercialization in 2021, a full product period of 2022–2024 and a planned expansion into 10 countries during 2025–2029. The expansion is presented as a future plan in the source.',
         'Milestones and plan as shown in the supplied SmartDarasa brochure.', 80),
        ('Sales projections',
         'The brochure’s projected sales are US$72,551 for 2024, US$239,814 for 2025, US$745,989 for 2026, US$1,822,093 for 2027, US$3,541,769 for 2028 and US$5,801,527 for 2029. These are projections from the brochure, not reported actual sales.',
         'Forecast values from the supplied SmartDarasa brochure.', 90),
        ('Management team',
         'The brochure names five management members and states a total team size of 12. The public profile includes the five members whose names and roles are shown; it does not infer identities for the other team members.',
         'Team names, titles and bios transcribed from the supplied SmartDarasa brochure.', 100),
        ('Advisors',
         'The brochure lists Jumanne Mtambaluke (Sahara Ventures), Tafara Muwandi, Ian Tarimo (Tai Tanzania) and Princely Glorious (Onastories) as advisors, with short biographies in the source document.',
         'Advisor names and affiliations transcribed from the supplied SmartDarasa brochure.', 110),
    ]
    for title, body, source_note, sort_order in sections:
        StartupPublicSection.objects.update_or_create(
            startup=startup, title=title,
            defaults={'body': body, 'source_note': source_note, 'sort_order': sort_order},
        )

    slides = [
        ('Interactive content and 3D models',
         'The brochure presents interactive 2D learning content and 360-degree 3D models for classroom topics.',
         'img/startups/smartdarasa-story-4.jpg',
         'SmartDarasa brochure page showing 2D interactive content and a 3D ammeter model.', 10),
        ('Virtual laboratory and augmented reality',
         'The brochure shows a virtual laboratory simulation and an AR learning experience.',
         'img/startups/smartdarasa-story-5.jpg',
         'SmartDarasa brochure page showing a virtual laboratory simulation and an augmented reality globe.', 20),
        ('Traction reported in the brochure',
         'Reported revenue, school reach, downloads, visitors and investment figures. See the details section for the source and reporting-period notes.',
         'img/startups/smartdarasa-story-7.jpg',
         'SmartDarasa brochure traction page with revenue, reach, app downloads, website visitors and funding.', 30),
        ('Management team',
         'The source brochure profiles five members of a team it describes as 12 people in total.',
         'img/startups/smartdarasa-story-12.jpg',
         'SmartDarasa brochure management team page.', 40),
    ]
    for title, caption, image_path, alt_text, sort_order in slides:
        StartupStorySlide.objects.update_or_create(
            startup=startup, title=title,
            defaults={
                'caption': caption, 'image_path': image_path,
                'alt_text': alt_text, 'sort_order': sort_order,
            },
        )

    team = [
        ('Elias', 'CEO', '2D, 3D and AR specialist. The brochure notes corporate experience at Shulesoft and Color Elephant and a BSc in Telecommunications Engineering.'),
        ('Kusiluka', 'CSO', 'The brochure describes experience starting more than 10 businesses, work at Muda and Eightskys, and a bachelor’s degree in Business Administration.'),
        ('Faith', 'COO', 'The brochure notes a BSc in Business Information Technology and experience in technology and business analysis.'),
        ('Happiness', 'CTO', 'The brochure describes technology team leadership experience at Youth for Africa and Kamal Steel, and a degree in ICT with management.'),
        ('Samwel', 'CFO', 'The brochure notes a degree in Accounting and Finance and more than four years of experience in finance and investment firms.'),
        ('Jumanne Mtambaluke', 'Advisor', 'The brochure describes him as a founder and innovator at Sahara Ventures with ideation and project management experience.'),
        ('Tafara Muwandi', 'Advisor', 'The brochure lists an MBA from Stanford and a master’s degree in Computer Science from Harrisburg, and says he created and sold a startup in the United States.'),
        ('Ian Tarimo', 'Advisor', 'The brochure identifies him as founder of Tai Tanzania and describes work with 3D animation, comics, television and radio for youth behavior change.'),
        ('Princely Glorious', 'Advisor', 'The brochure identifies him as co-founder of Onastories and describes work in augmented reality, virtual reality and digital brand storytelling.'),
    ]
    for sort_order, (name, title, bio) in enumerate(team, start=10):
        StartupTeamMember.objects.update_or_create(
            startup=startup, name=name,
            defaults={'title': title, 'bio': bio, 'sort_order': sort_order},
        )

    services = [
        ('Interactive STEM learning platform', 'Interactive 2D learning content, 3D models and augmented reality experiences.', 'education'),
        ('Virtual STEM laboratories', 'Online simulations that let students explore practical science experiments.', 'education'),
        ('Smart Labs for schools', 'The brochure describes tablet access, lab tools and practical digital learning content for schools.', 'education'),
        ('Smart APIs', 'The brochure describes APIs for integrating practical education content into other platforms.', 'technology'),
    ]
    for name, description, category in services:
        ServiceOffered.objects.update_or_create(
            startup=startup, name=name,
            defaults={'description': description, 'category': category},
        )

    funding_rows = [
        ('COSTECH', '24022.00', 'grant'),
        ('Diamond Do Goods', '10000.00', 'grant'),
        ('Amazon Web Services', '5000.00', 'other'),
        ('Schultz Family Foundation', '5000.00', 'other'),
        ('Mastercard Foundation', '14000.00', 'other'),
    ]
    for source, amount, funding_type in funding_rows:
        Funding.objects.update_or_create(
            startup=startup, source=source,
            defaults={
                'amount': amount, 'currency': 'USD', 'funding_type': funding_type,
                'status': 'received',
                'notes': 'Reported as raised in the supplied brochure; date not provided.',
            },
        )

    KPI.objects.update_or_create(
        startup=startup, metric_name='Revenue reported (2021–2022)',
        defaults={
            'metric_value': '9070.00', 'target_value': None,
            'period': 'annual', 'unit': 'USD',
        },
    )
    KPI.objects.filter(startup=startup, metric_name='Revenue reported (2021–2022)').update(
        date_recorded='2022-12-31'
    )
    startup.profile_completion = 44
    startup.save(update_fields=['profile_completion'])


def unseed_smartdarasa(apps, schema_editor):
    Startup = apps.get_model('staff', 'Startup')
    Startup.objects.filter(slug='smartdarasa').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_role_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupPublicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_sections', to='staff.startup')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StartupStorySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('image_path', models.CharField(help_text='Path relative to static/, for example img/startups/example-cover.jpg.', max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_slides', to='staff.startup')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StartupTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='startups/team/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='staff.startup')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.RunPython(seed_smartdarasa, migrations.RunPython.noop),
    ]
