# Generated by Django 5.2.17 on 2026-10-07 09:46

from django.db import migrations, models


def update_smartdarasa_from_dtbi_letters(apps, schema_editor):
    Startup = apps.get_model('staff', 'Startup')
    StartupPublicSection = apps.get_model('staff', 'StartupPublicSection')
    startup = Startup.objects.filter(slug='smartdarasa').first()
    if not startup:
        return

    startup.contact_person = 'Aginiwe J. Kusiluka'
    startup.contact_email = 'smartdarasa@gmail.com'
    startup.phone = '+255 654 705 765'
    startup.contact_address = 'P.O. Box 76324, Dar es Salaam, Tanzania'
    startup.year_incubated = 2024
    startup.source = 'SmartDarasa profile brochure and DTBi correspondence (2024)'
    startup.save(update_fields=[
        'contact_person', 'contact_email', 'phone', 'contact_address',
        'year_incubated', 'source',
    ])

    StartupPublicSection.objects.update_or_create(
        startup=startup,
        title='DTBi incubation history',
        defaults={
            'body': (
                'A July 2024 letter says SmartDarasa took part in DTBi’s out-house '
                'incubation support during the 2022–2023 cycle after its success in '
                'the MAKISATU challenge. SmartDarasa requested in-house incubation '
                'on 22 July 2024; DTBi’s letter dated 13 August 2024 says the request '
                'was accepted. The undated product brochure states a 12-person team, '
                'while the July 2024 request describes a 10-person team. These are '
                'source-specific counts and may reflect different dates.'
            ),
            'source_note': (
                'DTBi correspondence supplied with the profile: request dated '
                '22 Jul 2024 and acceptance dated 13 Aug 2024. The letters also '
                'provide the contact details shown to startup owners and DTBi staff.'
            ),
            'sort_order': 75,
        },
    )
    StartupPublicSection.objects.filter(
        startup=startup, title='Management team'
    ).update(
        body=(
            'The undated brochure names five management members and states a '
            'total team size of 12. A separate July 2024 DTBi request letter '
            'describes a 10-person team. The profile includes the named members '
            'and preserves both source-specific counts rather than assuming they '
            'refer to the same date.'
        ),
        source_note=(
            'Team names, titles and bios transcribed from the supplied brochure; '
            'the 10-person count comes from the July 2024 DTBi request letter.'
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_startuppublicsection_startupstoryslide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(update_smartdarasa_from_dtbi_letters, migrations.RunPython.noop),
    ]
