# Generated by Django 5.2.17 on 2026-10-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_smartdarasa_2025_profile_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('job', 'Job or Internship'), ('event', 'Event Invitation'), ('collaboration', 'Collaboration'), ('funding', 'Funding'), ('mentorship', 'Mentorship'), ('partnership', 'Partnership'), ('market_access', 'Market Access'), ('acceleration', 'Acceleration')], default='funding', max_length=20),
        ),
        migrations.CreateModel(
            name='StartupInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('job_offer', 'Job or Internship Opportunity'), ('collaboration', 'Collaboration or Partnership'), ('event', 'Event Invitation'), ('funding', 'Funding or Investment'), ('mentorship', 'Mentorship or Training'), ('product_demo', 'Product Demo or School Visit'), ('other', 'Other Opportunity')], max_length=20)),
                ('sender_name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='staff.startup')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['startup', 'status', 'created_at'], name='staff_start_startup_52e1d3_idx')],
            },
        ),
    ]
