# Generated by Django 5.2.17 on 2026-10-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_import_dtbi_workbook_startups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupstatushistory',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('terminated', 'Terminated')], max_length=20),
        ),
    ]
